language: ruby
sudo: false
cache: bundler
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
matrix:
  allow_failures:
    - rvm: 2.7.0
script:
  - bundle exec rubocop
  - bundle exec rspec
notifications:
  email:
    - team@wpscan.org
