name: Build Docker Images

on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  images:
    runs-on: ubuntu-latest

    steps:
      - name: checkout sources
        uses: actions/checkout@v2.3.4

      - name: Set tag to latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          echo "DOCKER_TAG=latest" >> $GITHUB_ENV

      - name: Set tag to release name
        if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/')
        run: |
          echo "DOCKER_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Check if DOCKER_TAG is set
        if: env.DOCKER_TAG == ''
        run: |
          echo DOCKER_TAG is not set!
          exit 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wpscanteam/wpscan:${{ env.DOCKER_TAG }}
